#The default group for people to be put into. Default is the only one extant at initialization.
default-group: 'default'
#Whether people should be disconnected if the plugin fails to initialize.
kick-on-failure: true
sql:
  #The only current supported type currently is mysql.
  type: mysql
  #The address of your MySQL installation. localhost should be fine if you don't know what this is.
  address: "localhost"
  #The database name to be used, this should only very rarely be changed.
  dbname: "OverPermissions"
  #The user from which to modify the database from. 'root' is fine if you don't know what this is.
  dbusername: "root"
  #The password to be used by mysql.
  dbpassword: ""
#Don't touch these options unless told otherwise. They could have adverse effects on your database and configuration.
internals:
  sql-schema-version: 1