package com.overmc.overpermissions.internal.databases;

import com.overmc.overpermissions.internal.datasources.GroupManagerDataSourceFactory;
import com.overmc.overpermissions.internal.datasources.TemporaryPermissionEntityDataSourceFactory;
import com.overmc.overpermissions.internal.datasources.UUIDDataSourceFactory;
import com.overmc.overpermissions.internal.datasources.UserDataSourceFactory;

public interface DatabaseMultiSourceFactory extends UUIDDataSourceFactory, UserDataSourceFactory, GroupManagerDataSourceFactory, TemporaryPermissionEntityDataSourceFactory {
}
